---
# tasks file for workstation

- name: include vars file
  include_vars:
    file: "{{ workstation_fella }}.yml"

- name: interact with API
  uri:
    url: "{{ item.url }}"
    method: "{{ item.method }}"
    body: "{{ item.body | default(omit) }}"
    body_format: "{{ item.body_format | default(omit) }}"
    return_content: "{{ item.return_content }}"
  register: "{{ item.register | default(omit) }}"
  loop: "{{ (workstation_api_interaction + workstation_default_api_interaction) | flatten(levels=1) }}"

- name: set hostname
  hostname:
    name: "{{ workstation_hostname }}"

- name: remove defined RPM packages
  dnf:
    name: "{{ item }}"
    state: absent
  loop: "{{ (workstation_rpm_packages_remove + workstation_default_rpm_packages_remove) | flatten(levels=1) }}"

- name: create required directory structures
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  loop: "{{ (workstation_required_dirs + workstation_default_required_dirs) | flatten(levels=1) }}"

- name: download required files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop: "{{ (workstation_download_files + workstation_default_download_files) | flatten(levels=1) }}"

- name: deploy required files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ (workstation_required_files + workstation_default_required_files) | flatten(levels=1) }}"

- name: add required RPM repositories
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl | default(omit) }}"
    mirrorlist: "{{ item.mirrorlist | default(omit) }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey | default(omit) }}"
    enabled: "{{ item.enabled }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck | default(omit) }}"
    state: present
  loop: "{{ (workstation_rpm_repos + workstation_default_rpm_repos) | flatten(levels=1) }}"

- name: add RPM repositories from RPM package
  dnf:
    name: "{{ workstation_rpm_repo_packages + workstation_default_rpm_repo_packages }}"
    state: installed
    disable_gpg_check: yes

- name: add RPM gpg keys
  rpm_key:
    key: "{{ item.gpgkey|regex_replace('file://', '') }}"
    state: present
  when: item.gpgkey is defined
  loop: "{{ (workstation_rpm_repos + workstation_default_rpm_repos) | flatten(levels=1) }}"

- name: install required RPM packages
  dnf:
    name: "{{ workstation_rpm_packages + workstation_default_rpm_packages }}"
    state: installed

- name: run commands as root
  command: "{{ item }}"
  loop: "{{ (workstation_run_command_root + workstation_default_run_command_root) | flatten(levels=1) }}"
  become_user: "root"
  become: yes
  changed_when: no

- name: run commands
  command: "{{ item }}"
  loop: "{{ (workstation_run_command + workstation_default_run_command) | flatten(levels=1) }}"
  become_user: "{{ workstation_username }}"

- name: clone repositories
  git:
    repo: "{{ item.value.repo }}"
    dest: "{{ item.value.dest }}"
    clone: yes
  loop: "{{ (workstation_git_repositories | combine(workstation_default_git_repositories)) | dict2items }}"
  become_user: "{{ workstation_username }}"

- name: deploy defined templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: "{{ item.backup }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ (workstation_required_templates + workstation_default_required_templates) | flatten(levels=1) }}"

- name: create additional groups
  user:
    name: "{{ item }}"
    state: present
  loop: "{{ (workstation_default_groups_additional_create + workstation_groups_additional_create) | flatten(levels=1) }}"

- name: append user to additional groups
  user:
    name: "{{ workstation_username }}"
    groups: "{{ item }}"
    append: yes
  loop: "{{ (workstation_default_groups_additional + workstation_groups_additional) | flatten(levels=1) }}"

# expects that docker is already installed
- name: add docker0 interface to trusted zone in firewalld
  firewalld:
    interface: "docker0"
    zone: trusted
    state: enabled
    permanent: True
    immediate: True
  when: workstation_docker_enabled

- name: enable required systemd units
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop: "{{ (workstation_enabled_systemd_units + workstation_default_enabled_systemd_units) | flatten(levels=1) }}"

- name: configure kernel parameters using sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ workstation_sysctl_parameters | flatten(levels=1) }}"

- name: configure dconf settings
  dconf:
    key: "{{ item.key }}"
    state: "{{ item.state }}"
    value: "{{ item.value }}"
  loop: "{{ (workstation_dconf + workstation_default_dconf) | flatten(levels=1) }}"
  become_user: "{{ workstation_username }}"

- name: include task files
  include_tasks: "{{ _workstation_include_task_item }}"
  loop: "{{ workstation_include_tasks | flatten(levels=1) }}"
  loop_control:
    loop_var: _workstation_include_task_item

- name: cleanup obsolete files
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ (workstation_cleanup_files + workstation_default_cleanup_files) | flatten(levels=1) }}"
